[project]
name = "skillsforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "deepagents>=0.3.5",
    "dotenv>=0.9.9",
    "langchain>=1.2.3",
    "langchain-experimental>=0.4.1",
    "tavily>=1.1.0",
]
